[package]
name = "zipkin"
version = "0.3.4"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "Apache-2.0"
description = "A library for collecting timing information about distributed computations"
repository = "https://github.com/palantir/rust-zipkin"
readme = "../README.md"
categories = ["network-programming", "web-programming"]
keywords = ["zipkin", "tracing"]

[features]
serde = ["zipkin-types/serde"]

[dependencies]
log = "0.4"
rand = "0.7"
thread-local-object = "0.1"

zipkin-types = { version = "0.1.0", path = "../zipkin-types" }
